# CC Assignment 4

### Q1.

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


#### (a)

In [2]:
print(arr + 2)

[3 4 5 6 7]


#### (b)

In [4]:
print(arr*3)

[ 3  6  9 12 15]


#### (c)

In [5]:
print(arr/2)

[0.5 1.  1.5 2.  2.5]


### Q2.

#### (a)

In [9]:
arr1 = np.array([1,2,3,6,4,5])
print(arr1[::-1])

[5 4 6 3 2 1]


#### (b)

#####         (i)

In [17]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
x_unique = np.unique(x)
x_count = [np.sum(x==i) for i in x_unique]
x_most_frequent = x_unique[np.argmax(x_count)]
x_indices = np.where(x == x_most_frequent)[0]
print('The most frequent value in array x :',x_most_frequent,' at indices :',x_indices)

The most frequent value in array x : 1  at indices : [0 5 7 8 9]


##### (ii)

In [19]:
y = np.array([1,1,1,2,3,4,2,4,3,3,3])
y_unique = np.unique(y)
y_count = [np.sum(y == i) for i in y_unique]
y_most_frequent = y_unique[np.argmax(y_count)]
y_indices = np.where(y == y_most_frequent)[0]
print('The most frequent value in array y:',y_most_frequent,' at indices :',y_indices)

The most frequent value in array y: 3  at indices : [ 4  8  9 10]


### Q3.

#### (a)

In [21]:
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2[0,1])

20


#### (b)

In [22]:
print(arr2[2,0])

70


### Q4.

In [39]:
sukhman = np.linspace(10,100,25)
print(sukhman)
print('\n')

print('Dimension of the array : ',sukhman.ndim)
print('\n')

print('Shape of the array : ',sukhman.shape)
print('\n')

print('Total elements in the array : ',sukhman.size)
print('\n')

print('Datatype of each element : ',sukhman.dtype)
print('\n')

print('Total number of bytes consumed by the array : ',sukhman.nbytes)
print('\n')

print('Transpose of the array :',sukhman.reshape(25,1))
print('\n')

print('Transpose of the array :',sukhman.T)
print('\n')

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Dimension of the array :  1


Shape of the array :  (25,)


Total elements in the array :  25


Datatype of each element :  float64


Total number of bytes consumed by the array :  200


Transpose of the array : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Transpose of the array : [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]




### Q5.

In [38]:
ucs420_sukhman = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_sukhman)
print('\n')

mean = np.mean(ucs420_sukhman)
print('Mean of the array : ',mean)
print('\n')

median = np.median(ucs420_sukhman)
print('Median of the array : ',median)
print('\n')

max_val = np.max(ucs420_sukhman)
print('Max value from the array : ',max_val)
print('\n')

min_val = np.min(ucs420_sukhman)
print('Min value from the arrray : ',min_val)
print('\n')

unique_val = np.unique(ucs420_sukhman)
print('Unique values of the arrray : ',unique_val)
print('\n')

reshaped_ucs420_sukhman = ucs420_sukhman.reshape(4,3)
print('Reshaped array : ',reshaped_ucs420_sukhman)
print('\n')

resized_ucs420_sukhman = np.resize(ucs420_sukhman,(2,3))
print('Resized array : ',resized_ucs420_sukhman)
print('\n')

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


Mean of the array :  43.333333333333336


Median of the array :  37.5


Max value from the array :  90


Min value from the arrray :  10


Unique values of the arrray :  [10 15 20 30 35 40 50 60 70 80 90]


Reshaped array :  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


Resized array :  [[10 20 30]
 [40 50 60]]


